//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Donation
    {
        public string TransactionID { get; set; }
        [Display(Name ="Donar Id")]
        public string DId { get; set; }
        [Display(Name ="NGO ID")]
        [Required(ErrorMessage ="NGO ID is required")]
        public string NgId { get; set; }
        [Display(Name ="Amount(Rs)")]
        [Required(ErrorMessage ="Amount can't be empty")]
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual Donar Donar { get; set; }
        public virtual NGO NGO { get; set; }
    }
}
