//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Raisedonation
    {
        [Display(Name="NGO Id")]
        public string NId { get; set; }
        [Required(ErrorMessage ="Amount Can't be empty")]
        public Nullable<int> Amount { get; set; }
    
        public virtual NGO NGO { get; set; }
    }
}
