//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharityManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Verification
    {
        [Display(Name ="NGO ID")]
        public string Id { get; set; }
        [Display(Name ="Proof Of Identity")]
        public string Image { get; set; }
        public string status { get; set; }
    
        public virtual NGO NGO { get; set; }
    }
}
